In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
# read csv files
df_post_CPI = pd.read_csv('../../Data/Downloads/Post/post_CPI.csv')
df_CPI_link = pd.read_csv('../../Data/Downloads/Pre/pre_CPI_link.csv')

In [9]:
gammaA = 50.85

In [62]:
df_CPI_link.loc[df_CPI_link.year_wst == 1935]

    year_wst  cpi_goods  cpi_agr  cpi_ind  ppi_agr  ppi_ind  epi_inv
62    1935.0     100.05    99.57    99.59    101.0     98.7     99.1

In [64]:
cpi_agr_link_1935_55 = df_CPI_link.loc[df_CPI_link.year_wst == 1955]['cpi_agr'].values[0]

In [65]:
cpi_agr_link_1955

36071.0

In [47]:
gammaA_1955 = gammaA / 100 * cpi_agr_link_1935_55

In [48]:
cpi_agr_1955 = df_post_CPI.loc[df_post_CPI.year_wst == 1955]['cpi_agr'].values[0]

In [50]:
cpi_agr_2005 = df_post_CPI.loc[df_post_CPI.year_wst == 2005]['cpi_agr'].values[0]

In [51]:
cpi_agr_link_1955_2005 = cpi_agr_2005 / cpi_agr_1955

In [54]:
cpi_agr_link_1955_2005

6.25

In [55]:
gammaA_1955

18342.1035

In [12]:
36071/96.3

374.56905503634476

In [58]:
gammaA_2005 = gammaA / 100 * cpi_agr_link_1935_55 * cpi_agr_link_1955_2005

In [60]:
gammaA_2005/12

9553.178906250001

In [7]:
df_post_CPI

    year_jpn  year_wst  cpi_goods  cpi_agr  cpi_ind
0         30      1955       22.9     16.0     27.7
1         31      1956       22.9     15.7     27.6
2         32      1957       23.7     16.3     28.3
3         33      1958       23.2     16.1     27.9
4         34      1959       23.3     16.3     27.6
5         35      1960       24.1     16.9     28.3
6         36      1961       25.1     18.0     29.4
7         37      1962       26.6     19.6     30.7
8         38      1963       28.5     21.9     32.3
9         39      1964       29.3     22.5     33.3
10        40      1965       31.1     25.5     34.2
11        41      1966       32.2     26.9     35.1
12        42      1967       33.4     28.6     36.0
13        43      1968       35.0     30.8     37.5
14        44      1969       36.8     32.7     39.0
15        45      1970       39.6     36.4     41.4
16        46      1971       41.8     37.2     44.0
17        47      1972       43.1     38.1     45.7
18        48      1973       48.5     43.4     51.3
19        49      1974       61.4     53.8     65.8
20        50      1975       67.5     61.8     70.7
21        51      1976       73.0     69.9     75.3
22        52      1977       77.1     74.9     79.1
23        53      1978       79.1     76.2     81.5
24        54      1979       81.3     78.2     83.8
25        55      1980       88.5     83.8     90.3
26        56      1981       92.8     88.5     94.2
27        57      1982       94.6     88.1     96.6
28        58      1983       96.0     89.9     97.8
29        59      1984       97.7     92.5     99.5
30        60      1985       99.0     94.4    100.6
31        61      1986       98.4     93.2    100.4
32        62      1987       97.0     90.6     99.7
33        63      1988       97.0     92.3     99.3
34         1      1989       98.7     94.0    100.9
35         2      1990      101.9    100.7    103.4
36         3      1991      105.6    107.5    106.9
37         4      1992      106.6    103.6    108.6
38         5      1993      107.0    104.4    109.0
39         6      1994      106.9    106.0    108.1
40         7      1995      105.4    102.4    106.9
41         8      1996      104.7    102.6    105.8
42         9      1997      106.2    103.9    107.0
43        10      1998      106.4    107.5    106.7
44        11      1999      105.6    104.6    106.5
45        12      2000      104.4     99.5    105.8
46        13      2001      102.9     99.4    103.8
47        14      2002      101.0     98.5    101.6
48        15      2003      100.2     99.6    100.3
49        16      2004      100.3    103.2     99.6
50        17      2005      100.0    100.0    100.0
51        18      2006      100.6    102.0    100.2
52        19      2007      100.6    102.6    100.0
53        20      2008      103.0    103.2    102.8
54        21      2009      100.5    101.3     99.7
55        22      2010       99.9    104.1     98.7