In [3]:
import pandas as pd

In [4]:
url = "https://warp.da.ndl.go.jp/info:ndljp/pid/11423429/www.stat.go.jp/data/chouki/zuhyou/22-14.xls"

In [5]:
df_original = pd.read_excel(url, header = None, index_col = None)

In [6]:
df_original

,0,1,2,3,4,5,6,7,8,9,...,36,37,38,39,40,41,42,43,44,45
0,２２－１４ 財・サービス分類指数（全国）（昭和３０年～平成２２年，昭和４０年度,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,～平成２１年度）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,22-14 Consumer Price Index by Goods and Servic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(平成17年=100),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,"1) Products, in principle, made by enterprise...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,2) To eliminate the gaps in upper-level indic...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,the indices from January 2008 are multipli...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,〔資料〕 総務省統計局統計調査部消費統計課物価統計室「消費者物価指数（CPI)」,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ホームページ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,"Source: Statistical Survey Department, Statis...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
stat_name_jpn = df_original.loc[0,0]

In [8]:
stat_name_eng = df_original.loc[2,0]

In [9]:
unit_jpn = df_original.loc[4,0]

In [10]:
unit_eng = df_original.loc[5,0]

In [11]:
# remove columns and rows with too many nulls
df_dropped = df_original.loc[df_original.notnull().sum(axis=1) > 2, df_original.notnull().sum() > 2]

In [16]:
df_original.to_csv('test.csv')

In [11]:
df_dropped.loc[10:,:]

,0,1,2,3,4,5,6,7,8,9,...,36,37,38,39,40,41,42,43,44,45
10,Calendar or fiscal year,NaN,General,Goods,"Goods, excluding fresh food",Agricultural & aquatic products,Fresh agricultural & aquatic products,Other agricultural & aquatic products,Rice,Industrial products,...,Imputed house rent,Other services,Services related to domestic duties,Services related to medical care & welfare,Services related to education,"Services related to communication, reading & r...",Durable goods\n2),Semi-durable goods\n2),Non-durable goods,"Public services & electricity, gas & water cha..."
11,昭和30年,C.Y.1955,-,22.9,-,16,-,22.5,22.9,27.7,...,-,6.87,-,-,-,-,133.6,-,-,24.1
12,31,1956,-,22.9,-,15.7,-,21.1,21.4,27.6,...,-,7.01,-,-,-,-,134.3,-,-,24.7
13,32,1957,-,23.7,-,16.3,-,22.1,22.4,28.3,...,-,7.08,-,-,-,-,137.2,-,-,24.9
14,33,1958,-,23.2,-,16.1,-,22.6,23,27.9,...,-,7.36,-,-,-,-,134.3,-,-,25.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,17,2005,100,100,100,99.5,99.6,99,99,100,...,100.1,99.8,100,100.2,100.1,99.5,98.4,100.1,100.2,100.1
109,18,2006,100.2,100.6,100.2,102.1,102.9,96.3,96.5,100.1,...,99.9,99.7,100.1,101.4,100.9,98.9,93.2,100.6,101.7,100.6
110,19,2007,100.6,101,100.6,102.6,103.8,94.6,94.6,100.5,...,99.8,99.9,100.2,104.2,101.5,98.8,89.4,101,102.8,101.1
111,20,2008,101.7,102.9,102.8,103.3,104.6,94.5,94.5,102.4,...,99.7,100.8,100.9,111.9,102.2,99.7,86.1,101.5,105.8,102.1
112,21,2009,100,99.9,99.8,100.8,101.8,93.8,93.7,99.4,...,99.5,100.1,100.7,122.8,102.9,97.4,81.7,100.5,102.6,100.7

In [13]:
# pick year, both in Japanese and western, and the price index for Goods, Agricultural and Aquatic, and industrial products
df_picked = df_dropped.loc[10:66, [0,1,3,5,9]]

In [14]:
df_picked

,0,1,3,5,9
10,Calendar or fiscal year,NaN,Goods,Agricultural & aquatic products,Industrial products
11,昭和30年,C.Y.1955,22.9,16,27.7
12,31,1956,22.9,15.7,27.6
13,32,1957,23.7,16.3,28.3
14,33,1958,23.2,16.1,27.9
15,34,1959,23.3,16.3,27.6
16,35,1960,24.1,16.9,28.3
17,36,1961,25.1,18,29.4
18,37,1962,26.6,19.6,30.7
19,38,1963,28.5,21.9,32.3
20,39,1964,29.3,22.5,33.3
21,40,1965,31.1,25.5,34.2
22,41,1966,32.2,26.9,35.1
23,42,1967,33.4,28.6,36
24,43,1968,35,30.8,37.5
25,44,1969,36.8,32.7,39
26,45,1970,39.6,36.4,41.4
27,46,1971,41.8,37.2,44
28,47,1972,43.1,38.1,45.7
29,48,1973,48.5,43.4,51.3
30,49,1974,61.4,53.8,65.8
31,50,1975,67.5,61.8,70.7
32,51,1976,73,69.9,75.3
33,52,1977,77.1,74.9,79.1
34,53,1978,79.1,76.2,81.5
35,54,1979,81.3,78.2,83.8
36,55,1980,88.5,83.8,90.3
37,56,1981,92.8,88.5,94.2
38,57,1982,94.6,88.1,96.6
39,58,1983,96,89.9,97.8
40,59,1984,97.7,92.5,99.5
41,60,1985,99,94.4,100.6
42,61,1986,98.4,93.2,100.4
43,62,1987,97,90.6,99.7
44,63,1988,97,92.3,99.3
45,平成元年,1989,98.7,94,100.9
46,2,1990,101.9,100.7,103.4
47,3,1991,105.6,107.5,106.9
48,4,1992,106.6,103.6,108.6
49,5,1993,107,104.4,109
50,6,1994,106.9,106,108.1
51,7,1995,105.4,102.4,106.9
52,8,1996,104.7,102.6,105.8
53,9,1997,106.2,103.9,107
54,10,1998,106.4,107.5,106.7
55,11,1999,105.6,104.6,106.5
56,12,2000,104.4,99.5,105.8
57,13,2001,102.9,99.4,103.8
58,14,2002,101,98.5,101.6
59,15,2003,100.2,99.6,100.3
60,16,2004,100.3,103.2,99.6
61,17,2005,100,100,100
62,18,2006,100.6,102,100.2
63,19,2007,100.6,102.6,100
64,20,2008,103,103.2,102.8
65,21,2009,100.5,101.3,99.7
66,22,2010,99.9,104.1,98.7

In [14]:
df_picked.columns = ['year_jpn', 'year_wst', 'pi_goods', 'pi_ag', 'pi_ind']

In [15]:
df_picked.loc[11,'year_jpn'] = 30

In [16]:
df_picked.loc[45,'year_jpn'] = 1

In [17]:
df_picked.loc[11,'year_wst'] = 1955

In [18]:
df_picked['year_jpn'] = df_picked['year_jpn'].astype(str).map(lambda x: x.rstrip('\u3000\u3000'))

In [19]:
df_picked['year_wst'] = df_picked['year_wst'].astype(str)

In [20]:
df_picked.to_csv('../../Data/Downloaded/post_price.csv', index = False)